#!/bin/sh

export DOTHOME=$HOME/dotfiles
 
git submodule update --init

ln -s $DOTHOME/config $HOME/.config

# Not everybody plays nice with XDG
ln -sf $DOTHOME/config/ctags.d/ $HOME/.ctags.d
ln -sf $DOTHOME/config/spacemacs $HOME/.spacemacs
ln -sf $DOTHOME/config/dlv $HOME/.dlv

ln -sf $DOTHOME/tcolors $HOME/.tcolors
ln -sf $DOTHOME/terminfo $HOME/.terminfo

ln -sf $DOTHOME/config/tmux/tmux.conf $HOME/.tmux.conf
ln -sf $DOTHOME/config/ruby/pryrc $HOME/.pryrc

ln -sf $DOTHOME/zsh/zprofile $HOME/.zprofile
ln -sf $DOTHOME/zsh/zshrc $HOME/.zshrc

if [ $(uname -a | grep "Darwin") ]; then
  brew install --cask amethyst
  brew bundle
fi

if [ $SPIN ]; then
  sudo apt purge -y neovim
  sudo add-apt-repository -y ppa:neovim-ppa/unstable
  sudo apt update && sudo apt install neovim -y

  xargs sudo apt-get -y install < packages.txt
  wget https://github.com/dandavison/delta/releases/download/0.11.2/git-delta_0.11.2_amd64.deb
  sudo dpkg -i git-delta_0.11.2_amd64.deb

  wget https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip 
  unzip exa-linux-x86_64-v0.10.1.zip
fi

