apiendpoint = "https://api.holepunch.io"
apikey = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzc3NDc4NDIsIm5iZiI6MTU3Nzc0Nzg0MiwianRpIjoiNThiYWIxNzItMmIwNC00NzMxLWE0NmMtMzEzMTFkYjBhOWRjIiwiZXhwIjoxNTgwMzM5ODQyLCJpZGVudGl0eSI6IjM1OWMxODkxLTc5YTEtNDFiYi1hNDIzLTE3YTE4NDk4ZWE1NCIsInR5cGUiOiJyZWZyZXNoIn0.QyZK09AzP6kjuvE67QEjW_NyrReJ65o_rDYc7iFMTg0"
baseurl = "http://holepunch.io"
crashreporting = true
loglevel = "ERROR"
privatekeypath = "/Users/stephenprater/.config/holepunch/holepunch_key.pem"
publickeypath = "/Users/stephenprater/.config/holepunch/holepunch_key.pub"
sshendpoint = "ssh://api.holepunch.io:22"
