apiendpoint = "https://api.holepunch.io"
apikey = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODQzODg3NDMsIm5iZiI6MTU4NDM4ODc0MywianRpIjoiYTFkY2RlZjYtMjk5OC00MTc2LWI1MTQtZGQwMTNlM2I4OTk0IiwiZXhwIjoxNTg2OTgwNzQzLCJpZGVudGl0eSI6IjM1OWMxODkxLTc5YTEtNDFiYi1hNDIzLTE3YTE4NDk4ZWE1NCIsInR5cGUiOiJyZWZyZXNoIn0.LQTv837CVFXD4bwmxoKGDHJO8O6v0uN8emn0CV-4s4w"
baseurl = "http://holepunch.io"
crashreporting = true
loglevel = "ERROR"
privatekeypath = "/Users/stephenprater/.config/holepunch/holepunch_key.pem"
publickeypath = "/Users/stephenprater/.config/holepunch/holepunch_key.pub"
sshendpoint = "ssh://api.holepunch.io:22"
