;extends
(([
  (decorated_definition)
  (class_definition)
  (function_definition)
  (if_statement)
  (for_statement)
  (while_statement)
  (with_statement)
  (try_statement)
  (block)
  (expression_statement)
  (dictionary)
  (list)
  (string)
] @_start @_end)
(#make-range! "range" @_start @_end)
)
