#!/bin/zsh

key_file=~/.oai-proxy-details

function needsUpdate() {
    [[ ! -f $key_file ]] && return 0

    lastModificationSeconds=$(date -r $key_file +%s)
    currentSeconds=$(date +%s)
    ((elapsedSeconds = currentSeconds - lastModificationSeconds))
    [[ $elapsedSeconds < 70000 ]] && return 1

    return 0
}

needsUpdate &&
    curl -s 'https://openai-proxy.shopify.io/hmac/personal' \
        -X 'POST' \
        -H 'content-type: application/json' \
        -H "Authorization: Bearer $(gcloud auth print-identity-token)" >$key_file

jq -r .$1 <$key_file
