# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [ -f "/opt/homebrew" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if [ -f "/usr/local" ]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

if [ -f "/opt/dev/sh/chruby.sh" ]; then
  source /opt/dev/sh/chruby/chruby.sh;
fi

if [ -f "/opt/dev/dev.sh" ]; then
  source /opt/dev/dev.sh
fi

if [ -f ~/.fzf.zsh ]; then
  source ~/.fzf.zsh
fi

# shortcut to this dotfiles path is $DOTHOME
export DOTHOME=$HOME/dotfiles

# source folder that we can `scd [tab]` into
export SOURCE_DIR=$HOME/src

# all of our zsh files
typeset -U config_files
setopt extended_glob
config_files=($DOTHOME/(^(plugins)/)#*zsh)

# load the path files
for file in ${(M)config_files:#*/path.zsh}
do
  source $file
done

# load everything but the path and completion files
for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}
do
  source $file
done

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit

zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:(rm|cp):*' ignore-line yes
zstyle ':completion:*' list-colors
zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:*' verbose true
zstyle ':completion:*:descriptions' format '%F{green}Completions for %B%d%b%f'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*:corrections' format '%B%d (errors: %e)%b'
zstyle ':completion:*:approximate:*' original true
zstyle ':completion:*:approximate:*' prompt 'Approximate to: %e'

setopt menucomplete

# load every completion after autocomplete loads
for file in ${(M)config_files:#*/completion.zsh}
do
  source $file
done

if [ type spin >/dev/null 2>&1 ]; then
  eval "$(spin completion)"
fi

# unset config_files

# Bash completions!
autoload -U +X bashcompinit && bashcompinit

# set cd autocompletion to commonly visited directories
setopt auto_cd
cdpath=(. ~/src $SOURCE_DIR/github.com/stephenprater $SOURCE_DIR/github.com/Shopify)
fpath=(path/to/zsh-completions/src $fpath)

zmodload -i zsh/parameter

autoload -U edit-command-line
autoload -U colors
zle -N edit-command-line
bindkey -M vicmd 'e' edit-command-line
bindkey -M vicmd ':' executed-named-command


# Configure the Prompt
setopt prompt_subst

autoload -U promptinit; promptinit

# Use EXA instead of LS
export EXA_COLORS="uu=38;5;239:ur=38;5;16:gr=38;5;16:tr=38;5;16:uw=32:sn=38;5;240:sb=38;5;240:da=38;5;242"

export EDITOR=nvim
export COMPOSE_HTTP_TIMEOUT=10000

if [ ! $SPIN ]; then
  export HOST_IP=$(ipconfig getifaddr en0)
fi

export GOPATH=$HOME/golang
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin:$DOTHOME/script

# # Load Environment Credenials from Keybase
# # if [ ! -f $DOTHOME/zsh/credentials.zsh ]; then
# #   cp $KEYBASE/credentials.zsh $DOTHOME/zsh/credentials.zsh
# #   source $DOTHOME/zsh/credentials.zsh
# # fi

autoload predict-on
predict-toggle() {
  ((predict-on=1-predict-on)) && predict-on || predict-off
}
zle -N predict-toggle
bindkey '' predict-toggle
zstyle ':predict' toggle true
zstyle ':predict' verbose true
